### ISSUE TITLE
DLS: Design Process

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#204]
It seems like we could expand this at a later date

_Design Process
Governance process for accepting additions/changes to the College DLS. To be determined after our base set of deliverable from Simpson Scarborough are in a stable state (release 1).

More detail to follow_

https://utsa-asc.github.io/college-dls/docs/process.html

**Comment by garza-utsa** [comment]
Going to assign this one to @Uri-E, thoughts but open to discussion:

- this page was setup initially as an aspirant page to document how we would develop new components or shepherd new requests that came in
- I think ideally, we would want to outline a template or format people outside ASC could use to develop a request of this type like:

Request type:  new component / component change request / variant change request

Brief explanation: 

Maybe a reference to an existing issue

For new components or change request that are outside minor padding or layout issues, i.e.- major changes.  We would also want a mock-up or design round or two along with a justification (why is this needed, why doesn't the existing component _x_ be used instead, etc type questions are answered).

- documentation would then just layout the process or workflow needed to go from request > design discussion > prototype > pull request.  We want to lead this discussion, but outline the process enough so that contributor can do the work

I will try and find a couple of good examples, but maybe this can already be done with a combination of some GitHub template features and a good markup page and a couple of helpful diagrams =)
