### ISSUE TITLE
DLS: Editor Configuration for CAS

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#253]
@lalov1, when you get a chance, go ahead and create an editor config on WALLEDEV for College-Prototype and apply the dist/college-dls/css/site.css file.  That should contain everything in a single css file.

I'll leave the configuration items up to you to test with =)

**Comment by lalov1** [comment]
@garza-utsa I added a couple of items to the WYSIWYG: 
https://user-images.githubusercontent.com/7785251/172189273-d83b962f-6eca-4027-9ff6-faa4847d7126.mov

One item we had was an image left and image right style because sometimes it was hard for editors to wrap images around text with the right padding. Not sure if we have something like this in the DLS I could add. I'm not sure if there is anything else I could add since it's pretty limited. I had thought about adding the angled buttons, but the font-awesome code is inside the button. If it was part of the style I could probably do that. We could always reconfigure it if you want to add it as a selectable style via the WYSIWYG. 

Feel free to see how the editor looks inside the Prototype website: 
https://walledev.it.utsa.edu/entity/open.act?type=folder&id=d1f60e3081736a1b3be11e063f9c0b5a

**Comment by lalov1** [comment]
Created issue #261 for the reconfiguration of the angled button.

**Comment by lalov1** [comment]
Going to close this out, but we could always create an issue to add any additional styles to the editor.
