### ISSUE TITLE
Accordion expand/collapse issues

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#273]
Not sure if this is a html coding issue or something funky going on with our classes, but the behavior is not consistent with the official accordion and can end up in a broken state

component: https://utsa-asc.github.io/college-dls/facult-image-updates/components/detail/accordion.html

reference component: https://getbootstrap.com/docs/5.1/components/accordion/

Steps to reproduce:
1. Expand the first accordion element
2. Expand the second accordion element

Issue:
On second expansion (step 2), the first accordion is collapsed (intended), but the state of the header row is not returned to it's collapsed state (stays grey with an "x"):

<img width="1191" alt="Screen Shot 2022-06-14 at 3 15 03 PM" src="https://user-images.githubusercontent.com/16828076/173680497-800bc14d-70b5-4dd7-8b21-eaba55085842.png">
 
You can get both element in a funky state by then collapsing the second element:

<img width="1208" alt="Screen Shot 2022-06-14 at 3 15 31 PM" src="https://user-images.githubusercontent.com/16828076/173680579-36485c82-79b8-4532-9ace-dee3be16a13b.png">

**Comment by garza-utsa** [comment]
@prd409-utsa, @lalov1  thinking about this more and looking at the .scss, we should probably have our styles not be bound to #accordion, as that's also the id that is used by bootstrap to enable to accordion functionality, this will break if we have multiple accordion sets on a page.  Should we use .accordion and override the default bootstrap styles?

**Comment by lalov1** [comment]
@garza-utsa @prd409-utsa Yep, we should probably only use the `#accordion` once on a page since it wouldn't meet accessibility standards when we reuse an ID. We could always enumerate the `#accordian` in Cascade so each accordion on a page has its own ID (`#accordion1`, `#accordion2`, etc.). You are right, we should probably target the `.accordian' since all the accordions should have that style.

**Comment by lalov1** [comment]
It would be nice to align the code closer to the bootstrap documentation since it looks like the vendor deviated quite a bit. I hope this should fix the funky behavior.

**Comment by prd409-utsa** [comment]
Upon investigating, this accordion expand/collapse issue, it is in SS version as well. It's just not noticeable because they only included one accordion in their demo.  When I added an additional accordion in browser to their demo, accordion expand/collapse performed the same as what we are getting in our repo. 

Very sneaky of them not to complete the functionality.

!https://development.simpsonscarborough.com/utsa/behavior.html

<img width="1590" alt="ss-demo_accordion" src="https://user-images.githubusercontent.com/92815346/174386275-f6c6db70-9f60-40b2-96a6-24024533eace.png">
