### ISSUE TITLE
variants in extra drawers

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#299]
once upon a time we had variants displayed in an extra column, instead of mixed in with the main navigation sidebar like this:
<img width="1793" alt="Screen Shot 2022-06-16 at 4 17 34 PM" src="https://user-images.githubusercontent.com/16828076/174166414-cab4fc15-a633-4487-9ef8-d0c0942bd9fa.png">

Any help finding where that feature went or what config option we need to use to get this back would be amazing =)

Not high priority, but our navigation sidebar is so long now, it would save us a lot of scrolling

**Comment by garza-utsa** [comment]
https://fractal.build/guide/components/configuration-reference.html#global-configuration-options. this page looks relatively new, I don't remember there being so many theme options, it might be one of these

**Comment by Uri-E** [comment]
Aight, I've combed through all the documentation and I can't find anything resembling that alternative navigation scheme :/

The 'collate' property renders the individual variants into the same preview window (SS attached). It would save some space, but we'd have to add some dividers with the name of the variant (CTA - 2 Button, etc.) to separate and label them. It's pretty easy to implement otherwise.

![Screen Shot 2022-06-17 at 5 25 56 PM](https://user-images.githubusercontent.com/105820950/174408693-106001a4-0272-49b8-bc82-674271175319.png)
.

**Comment by garza-utsa** [comment]
ah, think I found it, it's specifically a theme configuration, so it would go in your theme settings: navigation: 'split'

https://fractal.build/guide/web/default-theme.html#navigation

**Comment by garza-utsa** [comment]
I also do like the collate options, that would help us test the section level sections stacked against each other to make sure padding is consistent between variants, similar to #295
