### ISSUE TITLE
Headings Default Style

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#303]
I can't quite figure out how our headings are coming out not bold and not as large as it appears here https://utsa-asc.github.io/college-dls/components/detail/headline--default.html 

Any thoughts? 

<img width="493" alt="Screen Shot 2022-06-16 at 10 26 02 PM" src="https://user-images.githubusercontent.com/107521898/174218859-ff82f74e-9364-4db4-9166-c2633fcf8821.png">

I also don't know where the default rem sizes are stored, but if I could request a modification to the default size, here would be my recommendation

<img width="686" alt="Screen Shot 2022-06-16 at 10 23 52 PM" src="https://user-images.githubusercontent.com/107521898/174218653-cd6c8c8e-b2bb-4bea-8b22-3343a53de0da.png">

**Comment by garza-utsa** [comment]
going to assign this one to @Uri-E, we should definitely have consistency on our heading styles, especially in our regular content on generic pages, they should be matching up with our typography-headings section.  This may be another case of these styes being tied to a class instead of the defaults

**Comment by garza-utsa** [comment]
@kgarza-utsa default heading classes should reflect these classes now via @Uri-E 's PR #304 

Uriel will also take a look at the proposed changes in rem, first to make sure it's not going to disrupt any of our existing headings, he may suggest an alternative set of sizes if that's the case
