### ISSUE TITLE
DLS: sidebar removal of heading

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#376]
per our conversation while building KCEID pages:

- remove heading from sidebar
- restyle the first item in the side-nav-menu: bolder, no top bar, larger font-size

**Comment by kgarza-utsa** [comment]
@garza-utsa  could we not restyle the first item, that will disrupt all our sidebar because we uniquely code the sidebar to what we need it to be. we're all for hiding that "menu" block that shows on mobile though.

I did put this issue though with the first child li element when that first li is an expandable item #400
