### ISSUE TITLE
CMS: Links with the same name must have a similar purpose

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#490]
WCAG 2.1 Level AAA: [2.4.9 Link Purpose (Link Only)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only)

![Image](https://user-images.githubusercontent.com/7785251/192557035-8fd4af22-3f65-4b9f-aea7-425922b15630.png)

**Comment by prd409-utsa** [comment]
I like this. It sounds simple but the execution, not so much, as it is with most things of this nature!

The top nav links currently are for the universal Klesse site. EG: Programs is for ALL Programs (every Program in every discipline within CEID). But the right sidebar nav links are more granular (at the discipline/department level). 

It's second nature to me now from working in the site over the last few weeks but at first, it was very confusing.  

So maybe top nav links stay as-is due to space limitations
Right sidebar links change to - College Programs, College Faculty, etc ...
 or to be more descriptive and make it easier for the user to know exactly where they are - 
 Architecture Programs
 Architecture Faculty

but with names like Civil and Environmental Engineering and Construction Management being so looonnng, it will require using
CECM Programs
CECM Faculty
...?


Just some thoughts on all this... But it definitely needs to be addressed.

**Comment by lalov1** [comment]
I'm hoping we could add some aria attributes, and not have to rename any of the links: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

I think @garza had added the Accessibility Label to the links: 
<img width="670" alt="Screen Shot 2022-09-27 at 11 50 37 AM" src="https://user-images.githubusercontent.com/7785251/192587681-065ed9c6-cc95-4f44-a047-8270ecc22cfa.png">

I've added labels to many of the left nav links, but they don't seem to be working.

**Comment by garza-utsa** [comment]
yup, I've added this, but I think I may have missed a technical point, one of the duplicate links may be on navigation menus are also dropdowns.  I've added aria-labels for these items and am waiting for dubbot to re-crawl

**Comment by garza-utsa** [comment]
secondary fix for this implemented this morning, in the case of menus with dropdowns, like on Klesse, we have in the site navigation:

dropdown: Faculty
- page link: Faculty (#2 "identical link")

and then further (x2) on the BMCE subpages, the sidenav will also contain:

dropdown: Faculty (#3 "identical link")
- page link: Faculty Profiles

In the formats for side-navigation and header, I've added an aria-label for dropdown anchors that specifies the link label + "menu dropdown".,  for the BMCE sidenav, populating the ariaLabel also fixes that label's ambiguity.  Waiting for the next crawl to verify =)

**Comment by garza-utsa** [comment]
adding a similar aria-label to tab-group formatting, but I think the only errors left are related to photo galleries on Klesse for this error type

**Comment by lalov1** [comment]
I told Sean that he needs to go through the galleries to add better alt text since it's all the same. We could probably close the ticket for now.
