### ISSUE TITLE
CMS: Create XML Sitemap

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#573]
This is always good to have to submit to search engines for changes, especially after a redesign. There is some starter code on the Cascade Server Exchange: https://github.com/hannonhill/Velocity-Cookbook/tree/master/Sitemap-SEO

**Comment by garza-utsa** [comment]
there is a page content type in our old sites that output a html index of pages and an xml page using a version of the exchange code.  Never got confirmation from Marketing if the output generated was good.  Would you be willing to reach out to Judy in enrollment marketing to ask for an example output of the future.utsa.edu site map?  I know they have already done the verification work with collystring on their site maps generated via WordPress plugins.

**Comment by garza-utsa** [comment]
Created via query api:
https://walledev.it.utsa.edu/entity/open.act?id=4db9d9ee81736a1b4e58a078adaf100d&type=page

**Comment by garza-utsa** [comment]
The format on WALLE is only listing assets from the College-PROTOTYPE despite utilizing the .bySiteName() query method.  Making a local copy of the format seems to fix this, but this may be a 8.21 bug (this problem is not present on WALLEDEV running 8.22).  Leaving this open until cascade upgrades are complete.

**Comment by garza-utsa** [comment]
all versions of Cascade have been updated to 8.22.1, using .bySiteName() works as intended now.  Sitemaps are now deployed on WALLE and WALLEDEV
