### ISSUE TITLE
CMS: Content Type Standard Page Template - no breadcrumbs or sidebar menu

### ISSUE THREAD

**Issue by prd409-utsa** [utsa-asc/college-dls#632]
When choosing **+add content / default / pages / standard**   to create a new Standard page, the breadcrumbs do not show for the page and there is no sidebar menu, even with content in the top opening WYSIWYG.

https://walledev.it.utsa.edu/entity/open.act?id=3e0ac79b81736a1b324c023200c6f378&type=page

<img width="1658" alt="Screenshot 2023-10-17 at 11 14 03 AM" src="https://github.com/utsa-asc/college-dls/assets/92815346/c4261398-2c2a-4bf5-a05f-9e998fade027">

**Comment by garza-utsa** [comment]
[College-PROTOTYPE/_cms/formats/pages/standard] needs to have a fallback to default display breadcrumbs when no _page-config is found (sane defaults)

**Comment by garza-utsa** [comment]
same for [College-PROTOTYPE: /_cms/formats/components/wysiwygStandard] for showSideNav

**Comment by lalov1** [comment]
I added a check if it isn't equal to "No" the breadcrumbs won't show. This will work better since it was an explicit "Yes" before and didn't account for not having a _page-config:
https://walledev.it.utsa.edu/entity/open.act?id=d1f641b081736a1b3be11e0620abc9b5&type=format

For the side nav, I did something similar by ensuring an explicit "No" would have to be returned. Also, I added an "or" check if the side nav is empty. 
https://walledev.it.utsa.edu/entity/open.act?id=d1f640fc81736a1b3be11e06c637ab39&type=format

Right now, the only thing that shows is the college action buttons if there isn't a _page-config in the directory. I could add an internal note for the users that a _page-config isn't in the folder or the first WYSIWYG isn't empty. 

Everything seems okay, but let me know if y'all have any issues. If everything looks good, I'll move to Walle.
