### ISSUE TITLE
Strategy Question: BS Variables import

### ISSUE THREAD

**Issue by jsalazar** [utsa-asc/college-dls#9]
https://github.com/utsa-asc/college-dls/blob/18a0a8a0a073a3ab3605d4cd62b1dd5852555ef9/src/scss/import.scss#L11

In src/scss/import.scss 

    Why are we importing our our _variables.scss instead of 
    using Bootstrap variables (@import "../../node_modules/bootstrap/scss/variables";) 
    and then overriding it?

    See notes and examples within: 

https://github.com/utsa-asc/utsa-bs5-poc/blob/f705b6ee0acc99c07a91f036a2cf69ae81e2a55c/app/styles/utsa.bootstrap.scss#L55

**Comment by garza-utsa** [comment]
this is hold over from befor!, i copied a lot from our previous utsa-bootstrap repo setup, i see the preferred way of overriding default variables should be more like https://getbootstrap.com/docs/5.1/customize/sass/#variable-defaults

In the past, our unfamiliarity with bootstrap in general made it hard to know which variables came by default so the behavior was for us to copy the original bootstrap variables.scss file in its entirety, otherwise you gotta go hinting thru node_modules to find a specific variable name to override.  we can adopt the way above
